name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup terrafrom
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0
    
    - name: Terraform apply
      env:
        AZ_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
        AZ_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
        AZ_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      run: terraform apply -auto-approve -var=terraform/terraform.tfvars

    - name: DockerHub login
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Docker Pull Image
      run: docker pull ${{secrets.DOCKERHUB_USERNAME}}/mib-frontend:${{github.ref_name}}-${{github.sha}}

    - name: Config Webapp for Container
      run: |
        az webapp config cotainer set \
        --name mib-industries \
        --resource-group mib-rg \
        --docker-custom-image-name ${{secrets.DOCKERHUB_USERNAME}}/mib-frontend:${{github.ref_name}}-${{github.sha}} \
        --docker-registry-server-url https://index.docker.io/v1/ \
        --docker-registry-server-user ${{secrets.DOCKERHUB_USERNAME}} \
        --docker-registry-server-password ${{secrets.DOCKERHUB_PASSWORD}}